# Generated by Django 4.2 on 2023-04-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_remove_docente_apellido_paterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculinio')], default='F', max_length=1, null=True),
        ),
    ]
